server:
  port: 8081

spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false
  messages:
    basename: templates/addAlbums,templates/addSingers,templates/addSongs,templates/allAlbums,templates/allSingers,templates/allSongs
